server:
  port: 8080

spring:
  application:
    name: todoapp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo_db?characterEncoding=utf8&connectionCollation=utf8mb4_bin&sslMode=DISABLED&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: '0108'
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.messaging.MessagingAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration

bucket:
  name: todo-app-123214
  accessKey: ádfasdf
  secretKey: 12312
  region: ap-southeast-1