version: '3.8'

services:
  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: todo-test
    ports:
      - "3309:3306"

  springboot:
    build: ./be
    ports:
      - "8080:8080"
    environment:
      SPRING_TEST: 8080
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: todo-test
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql-db

  
  reactjs:
    build: ./fe
    environment:
      REACT_APP_BASE_API: http://springboot:8080
    ports:
      - "3000:3000"